# Generated by Django 4.2.4 on 2024-06-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0068_alter_validacao_ch_nome_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAberta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.TextField(blank=True, default=None, max_length=4000, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfc_app.curso')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'avaliações abertas',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='avaliacoes_abertas',
            field=models.ManyToManyField(related_name='avaliacoes_abertas', through='pfc_app.AvaliacaoAberta', to=settings.AUTH_USER_MODEL),
        ),
    ]
