# Generated by Django 4.2.4 on 2024-07-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0069_avaliacaoaberta_curso_avaliacoes_abertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='assinatura',
            field=models.FileField(blank=True, default='upload/certificado/', null=True, upload_to='upload/certificado/'),
        ),
    ]
