# Generated by Django 4.2.4 on 2024-07-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0072_curadoria_curso_priorizado_curso_curso_priorizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursopriorizado',
            options={'verbose_name_plural': 'cursos priorizados'},
        ),
        migrations.RenameField(
            model_name='cursopriorizado',
            old_name='nome_sugestão_acao',
            new_name='nome_sugestao_acao',
        ),
    ]
