# Generated by Django 4.2.4 on 2024-07-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0073_alter_cursopriorizado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('is_aberta', models.BooleanField(default=False)),
                ('ano_ref', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PesquisaCursosPriorizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano_ref', models.IntegerField(default=2024)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pesquisa_cursos_priorizados',
            field=models.ManyToManyField(blank=True, null=True, to='pfc_app.pesquisacursospriorizados'),
        ),
    ]
