# Generated by Django 4.2.4 on 2024-07-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0075_alter_cursopriorizado_options_alter_curso_nome_curso_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['nome_curso'], name='pfc_app_cur_nome_cu_d5c90f_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['coordenador'], name='pfc_app_cur_coorden_912f3c_idx'),
        ),
    ]
