# Generated by Django 4.2.4 on 2024-07-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0076_curso_pfc_app_cur_nome_cu_d5c90f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['participante'], name='pfc_app_ins_partici_6e0e85_idx'),
        ),
        migrations.AddIndex(
            model_name='inscricao',
            index=models.Index(fields=['curso'], name='pfc_app_ins_curso_i_7920fc_idx'),
        ),
    ]
