# Generated by Django 4.2.14 on 2024-07-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0077_inscricao_pfc_app_ins_partici_6e0e85_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nome']},
        ),
    ]
