# Generated by Django 4.2.14 on 2024-07-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0078_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome_curso']},
        ),
    ]
