# Generated by Django 4.2.14 on 2024-07-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0081_validacao_ch_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesquisa_cursos_priorizados',
            field=models.ManyToManyField(blank=True, to='pfc_app.pesquisacursospriorizados'),
        ),
    ]
