# Generated by Django 4.2.14 on 2024-07-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0084_lotacao_lotacaoespecifica_user_lotacao_especifica_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lotacao_especifica_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_especifica', to='pfc_app.lotacaoespecifica', verbose_name='Lotação Específica'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lotacao_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='pfc_app.lotacao', verbose_name='Lotação'),
        ),
    ]
