# Generated by Django 4.2.14 on 2024-07-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0085_alter_user_lotacao_especifica_fk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotacao',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='lotacaoespecifica',
            options={'ordering': ['nome']},
        ),
        migrations.AddIndex(
            model_name='lotacao',
            index=models.Index(fields=['nome'], name='pfc_app_lot_nome_6b5a60_idx'),
        ),
        migrations.AddIndex(
            model_name='lotacaoespecifica',
            index=models.Index(fields=['nome'], name='pfc_app_lot_nome_5d8752_idx'),
        ),
    ]
