# Generated by Django 4.2.14 on 2024-07-30 18:29

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0087_pagevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('nome', models.CharField(max_length=400)),
                ('email', models.EmailField(db_index=True, default='a@b.com', max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=40, null=True)),
                ('cargo', models.CharField(blank=True, max_length=400, null=True)),
                ('nome_cargo', models.CharField(blank=True, max_length=400, null=True)),
                ('categoria', models.CharField(blank=True, max_length=400, null=True)),
                ('grupo_ocupacional', models.CharField(blank=True, max_length=400, null=True)),
                ('origem', models.CharField(blank=True, max_length=400, null=True)),
                ('simbologia', models.CharField(blank=True, max_length=400, null=True)),
                ('tipo_atuacao', models.CharField(blank=True, max_length=400, null=True)),
                ('lotacao', models.CharField(blank=True, max_length=400, null=True)),
                ('lotacao_especifica', models.CharField(blank=True, max_length=400, null=True)),
                ('lotacao_especifica_2', models.CharField(blank=True, max_length=400, null=True, verbose_name='Lotação sigla')),
                ('classificacao_lotacao', models.CharField(blank=True, max_length=400, null=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('role', models.CharField(default='USER', max_length=40)),
                ('is_externo', models.BooleanField(default=False, verbose_name='É externo')),
                ('avatar', models.TextField(blank=True, max_length=100, null=True)),
                ('avatar_base64', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lotacao_especifica_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pfc_app.lotacaoespecifica', verbose_name='Lotação Específica')),
                ('lotacao_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pfc_app.lotacao', verbose_name='Lotação')),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical Usuários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
