# Generated by Django 4.2.14 on 2024-08-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0089_ajusteshoraaula_origempagamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajusteshoraaula',
            options={'verbose_name_plural': 'ajustes horas-aula'},
        ),
        migrations.RenameField(
            model_name='ajusteshoraaula',
            old_name='valor_instrutor_coordenador',
            new_name='valor_coordenador',
        ),
        migrations.RenameField(
            model_name='ajusteshoraaula',
            old_name='valor_instrutor_secundário',
            new_name='valor_instrutor_secundario',
        ),
    ]
