# Generated by Django 4.2.14 on 2024-08-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0091_arquivocurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Horário'),
        ),
    ]
