# Generated by Django 4.2.14 on 2024-12-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0094_historicaluser_carreira_user_carreira'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('username', models.CharField(max_length=400)),
                ('email', models.EmailField(default='a@b.com', max_length=254, unique=True)),
                ('celular', models.CharField(blank=True, max_length=40, null=True)),
                ('orgao_origem', models.CharField(blank=True, max_length=400, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo'),
        ),
    ]
