# Generated by Django 4.2.14 on 2025-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0096_alter_usercadastro_data_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtema',
            name='evento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pesquisacursospriorizados',
            name='ano_ref',
            field=models.IntegerField(default=2025),
        ),
    ]
