# Generated by Django 4.2.14 on 2025-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0097_subtema_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtema',
            name='evento',
        ),
        migrations.AddField(
            model_name='tema',
            name='evento',
            field=models.BooleanField(default=False),
        ),
    ]
