# Generated by Django 4.2.14 on 2025-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0099_validacao_ch_ano_validacao_ch_numero_sequencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='instrutor_principal',
            field=models.BooleanField(default=False),
        ),
    ]
