# Generated by Django 4.2.14 on 2025-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0100_inscricao_instrutor_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='instrutor_principal',
            field=models.BooleanField(default=False, verbose_name='Instrutor principal?'),
        ),
    ]
