# Generated by Django 4.2.14 on 2025-06-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0101_alter_inscricao_instrutor_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisacursospriorizados',
            name='forma_atendimento',
            field=models.CharField(blank=True, choices=[('PFC', 'PFC'), ('Curadoria', 'Curadoria')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pesquisacursospriorizados',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisa_cursos_priorizados', to='pfc_app.trilha'),
        ),
    ]
