# Generated by Django 4.2.4 on 2025-10-23 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0102_pesquisacursospriorizados_forma_atendimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorizacaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_ref', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorizacao_respostas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ano_ref'], name='pfc_app_pri_user_id_66e1a8_idx')],
                'unique_together': {('user', 'ano_ref')},
            },
        ),
    ]
