# Generated by Django 4.2.14 on 2025-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0103_priorizacaoresposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_primeiro_acesso',
            field=models.BooleanField(default=True, verbose_name='É o primeiro acesso'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_primeiro_acesso',
            field=models.BooleanField(default=True, verbose_name='É o primeiro acesso'),
        ),
    ]
