# Generated by Django 4.2.14 on 2025-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0104_historicaluser_is_primeiro_acesso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='is_primeiro_acesso',
            field=models.BooleanField(default=False, verbose_name='É o primeiro acesso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_primeiro_acesso',
            field=models.BooleanField(default=False, verbose_name='É o primeiro acesso'),
        ),
    ]
