# Generated by Django 4.2.14 on 2026-01-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfc_app', '0105_alter_historicaluser_is_primeiro_acesso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisacursospriorizados',
            name='ano_ref',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='validacao_ch',
            name='ano',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
    ]
