# Generated by Django 5.2.2 on 2025-06-09 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CursoConcluidoMoodle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("usuario_moodle_id", models.IntegerField()),
                ("curso_moodle_id", models.IntegerField()),
                ("nome_curso", models.CharField(max_length=255)),
                ("carga_horaria", models.CharField(max_length=50)),
                (
                    "usuario_pfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos_moodle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario_pfc", "curso_moodle_id")},
            },
        ),
    ]

