# Generated by Django 5.2.2 on 2025-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodle_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cursoconcluidomoodle",
            name="data_conclusao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

