# Generated by Django 5.2.2 on 2026-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodle_sync", "0002_cursoconcluidomoodle_data_conclusao"),
    ]

    operations = [
        migrations.CreateModel(
            name="CursoCompletoUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_curso_moodle", models.IntegerField()),
                ("carga_horaria_curso_moodle", models.CharField(max_length=50)),
                ("data_inicio_curso_moodle", models.DateTimeField(blank=True, null=True)),
                ("data_fim_curso_moodle", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-data_fim_curso_moodle", "-id"),
            },
        ),
    ]

