# Generated by Django 4.2.14 on 2026-05-13 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfc_app', '0106_alter_pesquisacursospriorizados_ano_ref_and_more'),
        ('moodle_sync', '0004_cursocompletousuario_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoMoodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('0', 'N/A')], default=None)),
                ('curso_moodle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='moodle_sync.cursoconcluidomoodle')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_moodle', to=settings.AUTH_USER_MODEL)),
                ('subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_moodle', to='pfc_app.subtema')),
            ],
            options={
                'verbose_name': 'avaliacao Moodle',
                'verbose_name_plural': 'avaliacoes Moodle',
                'indexes': [models.Index(fields=['curso_moodle', 'participante'], name='moodle_sync_curso_m_576d9f_idx')],
                'unique_together': {('curso_moodle', 'participante', 'subtema')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoAbertaMoodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.TextField(blank=True, default=None, max_length=4000, null=True)),
                ('curso_moodle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_abertas', to='moodle_sync.cursoconcluidomoodle')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_abertas_moodle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'avaliacao aberta Moodle',
                'verbose_name_plural': 'avaliacoes abertas Moodle',
                'indexes': [models.Index(fields=['curso_moodle', 'participante'], name='moodle_sync_curso_m_96f40e_idx')],
                'unique_together': {('curso_moodle', 'participante')},
            },
        ),
    ]
