# Generated by Django 4.2.14 on 2026-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificados', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(check=models.Q(('position__lte', 2)), name='classificados_image_position_lte_2'),
        ),
    ]
