# Generated by Django 4.2.14 on 2026-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificados', '0002_productimage_classificados_image_position_lte_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='ativo pelo anunciante'),
        ),
    ]
