# Generated by Django 4.2.14 on 2026-09-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificados', '0003_product_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='lido pelo anunciante em'),
        ),
    ]
