# Generated by Django 5.2.2 on 2025-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='is_aberta',
            field=models.BooleanField(default=False),
        ),
    ]
