# Generated by Django 4.2.14 on 2026-09-17 13:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import leilao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('origin', models.CharField(choices=[('seplag', 'SEPLAG'), ('external', 'Externo')], default='seplag', max_length=20, verbose_name='origem')),
                ('starts_at', models.DateTimeField(verbose_name='início')),
                ('ends_at', models.DateTimeField(verbose_name='fim')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leilao_auctions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'leilão',
                'verbose_name_plural': 'leilões',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço inicial')),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço mínimo para venda')),
                ('increment_type', models.CharField(choices=[('fixed', 'Valor fixo'), ('percentage', 'Percentual')], default='fixed', max_length=20, verbose_name='tipo de incremento')),
                ('increment_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='incremento')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início')),
                ('ends_at', models.DateTimeField(verbose_name='fim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='leilao.auction', verbose_name='leilão')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leilao_products', to=settings.AUTH_USER_MODEL, verbose_name='criador')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leilao/products/%Y/%m/', validators=[leilao.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='foto')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leilao.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leilao_bids', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='leilao.product')),
            ],
            options={
                'ordering': ['-amount', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='leilao_prod_created_be2e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ends_at'], name='leilao_prod_ends_at_898c50_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['product', '-amount'], name='leilao_bid_product_a18118_idx'),
        ),
    ]
