# Generated by Django 4.2.14 on 2026-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator_notified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='notification_error',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='winner_notified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
