# Generated by Django 4.2.14 on 2026-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0002_product_creator_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Opcional. Sem data, o leilão não tem encerramento próprio.', null=True, verbose_name='fim'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Opcional. Sem data, o leilão fica disponível imediatamente.', null=True, verbose_name='início'),
        ),
    ]
