# Generated by Django 6.0.1 on 2026-01-30 12:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('assunto', models.CharField(max_length=200)),
                ('corpo', models.TextField(help_text='Use tags no formato [pedido_empresa_nome], [user_email], etc.')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TagTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome sem colchetes. Ex: pedido_empresa_nome para usar como [pedido_empresa_nome].', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Use snake_case: ex. pedido_empresa_nome')])),
                ('contexto_alias', models.CharField(help_text='Chave do contexto: ex. user, pedido, empresa.', max_length=40)),
                ('path', models.CharField(help_text="Caminho com '.' (profundidade livre). Ex: empresa.nome ou perfil.endereco.cidade", max_length=300)),
                ('padrao', models.CharField(blank=True, default='', max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(help_text='Model do objeto raiz esperado para este contexto_alias.', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
