# Generated by Django 4.2.14 on 2026-09-17 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mensageria.models


class Migration(migrations.Migration):

    dependencies = [
        ('mensageria', '0002_emailstatusbatch_emailstatusbatchitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailStatusBatchAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mensageria.models.email_status_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=127)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mensageria.emailstatusbatch')),
            ],
            options={
                'verbose_name': 'anexo do lote de e-mails',
                'verbose_name_plural': 'anexos do lote de e-mails',
                'ordering': ['id'],
            },
        ),
    ]
