# Generated by Django 4.2.14 on 2026-09-17 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mensageria.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensageria', '0003_emailstatusbatchattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=32)),
                ('file', models.FileField(upload_to=mensageria.models.email_send_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=127)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_send_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'anexo de envio de e-mail',
                'verbose_name_plural': 'anexos de envio de e-mail',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='EmailStatusBatchAttachment',
        ),
    ]
